### ISSUE TITLE
Simplify CSS further for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [anderbay/prj-rev-bwfs-dasmoto#5]
You did a great job simplifying the CSS for the font-family property by applying it to the html selector. There are a few more properties shared among multiple selectors which you can simplify further. 

Here is how you might simplify it for the other properties,

```css
html {
  font-family: Helvetica;
  font-weight: bold;
}

header{
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
}

h1 {
  font-size: 100px;
  color: khaki;
  text-align: center;
}

h2 {
  font-size: 32px;
  color: white;
}

#Brush_Title {
  background-color:mediumspringgreen;
}

#Frame_Title {
  background-color:lightcoral;
}

#Paint_Title {
  background-color:skyblue;
}

p{
  font-size: 16px;
  color: black;
  font-weight: normal;
}

.blue_text {
  color: blue;
}
```
